### ISSUE TITLE
Version 1

### ISSUE THREAD

**Issue by sithmel** [sithmel/obj-sieve#4]
- [x] documentation
- [x] filter expressions:
  - [x] and / or
  - [x] nested properties. Like heroes[:][base.address.name=batcave]
  - [x] custom functions ?
  - [x] forked expressions
  - [x] multiple expression (comma separated)
- [x] escaping in expressions
